export const PAGINATION_CONFIG = {
  MAX_LIMIT: 1000,
  DEFAULT_LIMIT: 100,
  MIN_LIMIT: 1,
  MAX_OFFSET: 10000,
  DEFAULT_OFFSET: 0
};

export const { MAX_LIMIT, DEFAULT_LIMIT, MIN_LIMIT, MAX_OFFSET, DEFAULT_OFFSET } = PAGINATION_CONFIG;
